// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvLUsFJF6ICcuj0ozZZa04uv7UNwmGEDo',
    appId: '1:559880713537:web:e41601e163257a027eddc0',
    messagingSenderId: '559880713537',
    projectId: 'quizapp-f2190',
    authDomain: 'quizapp-f2190.firebaseapp.com',
    storageBucket: 'quizapp-f2190.firebasestorage.app',
    measurementId: 'G-DB7R7D7F6Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzJ2L22ijb6utvEbeFhXHqa34Ajd86HeA',
    appId: '1:559880713537:android:bc4f56f00237fb367eddc0',
    messagingSenderId: '559880713537',
    projectId: 'quizapp-f2190',
    storageBucket: 'quizapp-f2190.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSEPQ0nAbP7jn0G6Zp7ZVoRZrqKxLxqro',
    appId: '1:559880713537:ios:a3566ec5e15dc9847eddc0',
    messagingSenderId: '559880713537',
    projectId: 'quizapp-f2190',
    storageBucket: 'quizapp-f2190.firebasestorage.app',
    androidClientId: '559880713537-5tuc2f0m79vfh97br2ufda8jo9bpo2av.apps.googleusercontent.com',
    iosClientId: '559880713537-np5cst2gnq98l0op4ntpb06fr955fq92.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSEPQ0nAbP7jn0G6Zp7ZVoRZrqKxLxqro',
    appId: '1:559880713537:ios:a3566ec5e15dc9847eddc0',
    messagingSenderId: '559880713537',
    projectId: 'quizapp-f2190',
    storageBucket: 'quizapp-f2190.firebasestorage.app',
    androidClientId: '559880713537-5tuc2f0m79vfh97br2ufda8jo9bpo2av.apps.googleusercontent.com',
    iosClientId: '559880713537-np5cst2gnq98l0op4ntpb06fr955fq92.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvLUsFJF6ICcuj0ozZZa04uv7UNwmGEDo',
    appId: '1:559880713537:web:003f4f9d4a98dccc7eddc0',
    messagingSenderId: '559880713537',
    projectId: 'quizapp-f2190',
    authDomain: 'quizapp-f2190.firebaseapp.com',
    storageBucket: 'quizapp-f2190.firebasestorage.app',
    measurementId: 'G-F4P7H6FRJ7',
  );
}
